#pragma once

#include <Lib\Novel\Ncpp\Common\commonLib.h>
#include <Lib\Novel\Ncv\OpenCV\CvIncludes.h>
#include <Lib\Novel\Ncv\VectorVal.h>
#include <Lib\Novel\Ncv\OpenCV\Types.h>
#include <Lib\Novel\Ncv\OpenCV\killers.h>
#include <Lib\Novel\Ncv\OpenCV\error.h>
#include <Lib\Novel\Ncv\OpenCV\PixelTypes.h>
#include <Lib\Novel\Ncv\OpenCV\Channel.h>
#include <Lib\Novel\Ncv\OpenCV\Image.h>
#include <Lib\Novel\Ncv\OpenCV\funcs1.h>
//#include <Lib\Novel\Ncv\ConvKernel.h>
#include <Lib\Novel\Ncv\OpenCV\Hsv.h>
//#include <Lib\Novel\Ncv\HistoGram.h>
#include <Lib\Novel\Ncv\InitLib.h>
//#include <Lib\Novel\Ncv\RegionSegmentor.h>
//#include <Lib\Novel\Ncv\RegionSegmentor2.h>
//#include <Lib\Novel\Ncv\RegionSegmentor3.h>
//#include <Lib\Novel\Ncv\RegionSegmentor4.h>
//#include <Lib\Novel\Ncv\RegionSegmentor5.h>
//#include <Lib\Novel\Ncv\RegionSegmentor6.h>
//#include <Lib\Novel\Ncv\RegionSegmentor7.h>
//#include <Lib\Novel\Ncv\RegionSegmentor8.h>
//#include <Lib\Novel\Ncv\RegionSegmentor9.h>
//#include <Lib\Novel\Ncv\RegionSegmentor10.h>
//#include <Lib\Novel\Ncv\RegionSegmentor11.h>
//#include <Lib\Novel\Ncv\RegionSegmentor12.h>
//#include <Lib\Novel\Ncv\RegionSegmentor13.h>
//#include <Lib\Novel\Ncv\RegionSegmentor14.h>
//#include <Lib\Novel\Ncv\RegionSegmentor15.h>
//#include <Lib\Novel\Ncv\RegionSegmentor16.h>
//#include <Lib\Novel\Ncv\RegionSegmentor17.h>
//#include <Lib\Novel\Ncv\RegionSegmentor18.h>
//#include <Lib\Novel\Ncv\RegionSegmentor19.h>
//#include <Lib\Novel\Ncv\RegionSegmentor20.h>
//#include <Lib\Novel\Ncv\RegionSegmentor21.h>
//#include <Lib\Novel\Ncv\RegionSegmentor22.h>
//#include <Lib\Novel\Ncv\RegionSegmentor23.h>
//#include <Lib\Novel\Ncv\RegionSegmentor24.h>
//#include <Lib\Novel\Ncv\RegionSegmentor25.h>
//#include <Lib\Novel\Ncv\RegionSegmentor26.h>
//#include <Lib\Novel\Ncv\RegionSegmentor27.h>
//#include <Lib\Novel\Ncv\RegionSegmentor28.h>
//#include <Lib\Novel\Ncv\RegionSegmentor29.h>
//#include <Lib\Novel\Ncv\RegionSegmentor30.h>
//#include <Lib\Novel\Ncv\RegionSegmentor31.h>
//#include <Lib\Novel\Ncv\RegionSegmentor32.h>
//#include <Lib\Novel\Ncv\RegionSegmentor33.h>
//#include <Lib\Novel\Ncv\RegionSegmentor34.h>
//#include <Lib\Novel\Ncv\RegionSegmentor35.h>
//#include <Lib\Novel\Ncv\RegionSegmentor36.h>
//#include <Lib\Novel\Ncv\RegionSegmentor37.h>
//#include <Lib\Novel\Ncv\RegionSegmentor38.h>
//#include <Lib\Novel\Ncv\RegionSegmentor39.h>
//#include <Lib\Novel\Ncv\RegionSegmentor40.h>
//#include <Lib\Novel\Ncv\RegionSegmentor41.h>
//#include <Lib\Novel\Ncv\RegionSegmentor42.h>
//#include <Lib\Novel\Ncv\RegionSegmentor43.h>
//#include <Lib\Novel\Ncv\RegionSegmentor44.h>
//#include <Lib\Novel\Ncv\RegionSegmentor45.h>
//#include <Lib\Novel\Ncv\RegionSegmentor46.h>
//#include <Lib\Novel\Ncv\RegionSegmentor47.h>
//#include <Lib\Novel\Ncv\RegionSegmentor48.h>
//#include <Lib\Novel\Ncv\RegionSegmentor49.h>
//#include <Lib\Novel\Ncv\RegionSegmentor50.h>
//#include <Lib\Novel\Ncv\RegionSegmentor51.h>
//#include <Lib\Novel\Ncv\AdaptiveConv.h>
//#include <Lib\Novel\Ncv\AdaptiveConv2.h>
//#include <Lib\Novel\Ncv\CusteringTries.h>
//#include <Lib\Novel\Ncv\ClusteringMgr.h>
//#include <Lib\Novel\Ncv\ImageClusteringMgr.h>
//#include <Lib\Novel\Ncv\SignalOneDim.h>
//#include <Lib\Novel\Ncv\SobelBuilder.h>
//#include <Lib\Novel\Ncv\PNEdgeBuilder.h>
#include <Lib\Novel\Ncv\IOMgr.h>
//#include <Lib\Novel\Ncv\LinePath.h>
#include <Lib\Novel\Ncv\LinePathInt.h>
#include <Lib\Novel\Ncv\Signal1D.h>
#include <Lib\Novel\Ncv\Signal1DViewer.h>
//#include <Lib\Novel\Ncv\Filter1D.h>
//#include <Lib\Novel\Ncv\ConvFilter1D.h>
//#include <Lib\Novel\Ncv\LinearColorFilter1D.h>
//#include <Lib\Novel\Ncv\LinearAvgFilter1D.h>
//#include <Lib\Novel\Ncv\LinearDiffFilter1D.h>
//#include <Lib\Novel\Ncv\ImageLineViewer.h>
//#include <Lib\Novel\Ncv\ColorFilter1D.h>
//#include <Lib\Novel\Ncv\CompositeColorFilter1D.h>
//#include <Lib\Novel\Ncv\ColorFilter1DSystem.h>
//#include <Lib\Novel\Ncv\AbsFilter1D.h>
//#include <Lib\Novel\Ncv\ScaleFixFilter1D.h>
//#include <Lib\Novel\Ncv\PeakCleanerFilter1D.h>
//#include <Lib\Novel\Ncv\PeakMarkerFilter1D.h>
//#include <Lib\Novel\Ncv\ValleyMaximizerFilter1D.h>
//#include <Lib\Novel\Ncv\ImageLineViewer2.h>
//#include <Lib\Novel\Ncv\ImageLineViewer3.h>
//#include <Lib\Novel\Ncv\SerialColorMgr.h>
//#include <Lib\Novel\Ncv\ConflictScanner.h>
//#include <Lib\Novel\Ncv\ConflictScanner2.h>
//#include <Lib\Novel\Ncv\FiltSysDebug.h>
//#include <Lib\Novel\Ncv\ValleyMarkerFilter1D.h>
//#include <Lib\Novel\Ncv\DiagonalLinePath.h>
//#include <Lib\Novel\Ncv\NegDiagonalLinePath.h>
//#include <Lib\Novel\Ncv\MaxFilter1D.h>
//#include <Lib\Novel\Ncv\BadRootScanner.h>
//#include <Lib\Novel\Ncv\CircleContPath.h>
//#include <Lib\Novel\Ncv\CircleContourOfPix.h>
//#include <Lib\Novel\Ncv\CircleContourOfPix2.h>
//#include <Lib\Novel\Ncv\CircleContourOfPix3.h>
//#include <Lib\Novel\Ncv\CircleContourOfPix4.h>
//#include <Lib\Novel\Ncv\CircleContourOfPix5.h>
#include <Lib\Novel\Ncv\MultiColorSignal1DViewer.h>
//#include <Lib\Novel\Ncv\CircDiff.h>
//#include <Lib\Novel\Ncv\CircDiff2.h>
//#include <Lib\Novel\Ncv\SlideMgr.h>
//#include <Lib\Novel\Ncv\LineStepper.h>
//#include <Lib\Novel\Ncv\LineStepperByAngle.h>
//#include <Lib\Novel\Ncv\ScanDirMgr.h>
//#include <Lib\Novel\Ncv\ImgDataMgr_Simple.h>
//#include <Lib\Novel\Ncv\ImgDataMgr_Simple_2.h>
//#include <Lib\Novel\Ncv\ImgDataMgr_C7.h>
//#include <Lib\Novel\Ncv\ImgDataMgr_CovMat.h>
//#include <Lib\Novel\Ncv\IImgDataMgr.h>
//#include <Lib\Novel\Ncv\ImgDataElm_Simple.h>
//#include <Lib\Novel\Ncv\ScanDirMgrColl.h>
//#include <Lib\Novel\Ncv\SubGradMgr.h>
//#include <Lib\Novel\Ncv\ImgGradMgr.h>
//#include <Lib\Novel\Ncv\ImgGradMgr_2.h>
//#include <Lib\Novel\Ncv\ImgAvgingMgr.h>
//#include <Lib\Novel\Ncv\Avging_ScanDirMgrExt.h>
//#include <Lib\Novel\Ncv\DeltaSignal.h>
//#include <Lib\Novel\Ncv\Filt1D2.h>
//#include <Lib\Novel\Ncv\SingFilt1D2.h>
//#include <Lib\Novel\Ncv\Filt1D2DataMgr.h>
//#include <Lib\Novel\Ncv\AvgFilt1D2.h>
//#include <Lib\Novel\Ncv\Filt1D2System.h>
//#include <Lib\Novel\Ncv\Filt1D2SysProto.h>
//#include <Lib\Novel\Ncv\ScanTryMgr.h>
//#include <Lib\Novel\Ncv\DifFilt1D2.h>
//#include <Lib\Novel\Ncv\PeakMarkerFilt1D2.h>
//#include <Lib\Novel\Ncv\AbsFilt1D2.h>
//#include <Lib\Novel\Ncv\ZeroCrossingFilt1D2.h>
//#include <Lib\Novel\Ncv\MaxFilt1D2.h>
//#include <Lib\Novel\Ncv\EdgeScanMgr.h>
//#include <Lib\Novel\Ncv\EdgeScan.h>
//#include <Lib\Novel\Ncv\ScanTryMgr2.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_3.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_4.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_5.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_6.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_7.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_8.h>
//#include <Lib\Novel\Ncv\ScanTryMgr_9.h>
//#include <Lib\Novel\Ncv\ScanTryDbg.h>
//#include <Lib\Novel\Ncv\ZeroCrossing_2_Filt1D2.h>
//#include <Lib\Novel\Ncv\Ptr_Filt1D2DataMgr.h>
//#include <Lib\Novel\Ncv\ImageWatershedMgr.h>
//#include <Lib\Novel\Ncv\IImgPopulation.h>
//#include <Lib\Novel\Ncv\ImgPopulation_Simple.h>
//#include <Lib\Novel\Ncv\ImgPopulation_C7.h>
//#include <Lib\Novel\Ncv\ImgPopulation_CovMat.h>
//#include <Lib\Novel\Ncv\ImgSegDataMgr.h>
//#include <Lib\Novel\Ncv\ImgSeg_EvalMgr.h>
//#include <Lib\Novel\Ncv\ImgSeg_Method_EvalMgr.h>
//#include <Lib\Novel\Ncv\ImgSeg_GrandMethod_EvalMgr.h>
//#include <Lib\Novel\Ncv\CBIS_Berkeley_Executer.h>
//#include <Lib\Novel\Ncv\PeakMarkerFilt1D2_2.h>
//#include <Lib\Novel\Ncv\RgnSegmDiameter.h>
//#include <Lib\Novel\Ncv\ColorTryMgr.h>
//#include <Lib\Novel\Ncv\ImgDataElm_C7.h>
//#include <Lib\Novel\Ncv\ImgDataElm_C07.h>
//#include <Lib\Novel\Ncv\ImgDataElm_CovMat.h>
//#include <Lib\Novel\Ncv\ImgRotationMgr.h>
//#include <Lib\Novel\Ncv\ImgRotationMgr_3.h>
#include <Lib\Novel\Ncv\ImgSizeRotation.h>
#include <Lib\Novel\Ncv\ImgSizeRotationColl.h>
//#include <Lib\Novel\Ncv\ImageLineItr.h>
//#include <Lib\Novel\Ncv\ImageLineItrProvider.h>
//#include <Lib\Novel\Ncv\ImageItrMgr.h>
//#include <Lib\Novel\Ncv\ImageRotationMgr_Ex.h>
//#include <Lib\Novel\Ncv\IImgDataMgr_2.h>
//#include <Lib\Novel\Ncv\ImgDataMgr_2_CovMat.h>
//#include <Lib\Novel\Ncv\ImageNbrMgr.h>
//#include <Lib\Novel\Ncv\IImgDataGradMgr.h>
//#include <Lib\Novel\Ncv\ImgDataGradMgr_CovMat.h>
//#include <Lib\Novel\Ncv\IImgDataMgr_2_FactorySet.h>
//#include <Lib\Novel\Ncv\ImgDataMgr_2_FactorySet_CovMat.h>
//#include <Lib\Novel\Ncv\ImageRotationMgr_Friend.h>
//#include <Lib\Novel\Ncv\ImgBiMixGrad.h>
//#include <Lib\Novel\Ncv\ImgScanMgr.h>
//#include <Lib\Novel\Ncv\ImgClusteringTry.h>
#include <Lib\Novel\Ncv\ImageAccessor.h>
#include <Lib\Novel\Ncv\Image_Operations.h>
#include <Lib\Novel\Ncv\TempImageAccessor.h>
#include <Lib\Novel\Ncv\Line_Operations.h>
#include <Lib\Novel\Ncv\ImageAccessorOperations.h>
#include <Lib\Novel\Ncv\Element_Operations_VectorVal.h>
#include <Lib\Novel\Ncv\Element_Operations_F32ColorVal.h>
#include <Lib\Novel\Ncv\Element_Operations.h>
#include <Lib\Novel\Ncv\PixelStandevInfo.h>
#include <Lib\Novel\Ncv\ConflictInfo.h>


//#include <Lib\Novel\Ncv\LocHist\ImgDataGradMgr_LocHist.h>
//#include <Lib\Novel\Ncv\LocHist\ImgDataMgr_2_FactorySet_LocHist.h>
//#include <Lib\Novel\Ncv\LocHist\ImgDataMgr_2_LocHist.h>

//#include <Lib\Novel\Ncv\GridColorPalette.h>

//#include <Lib\Novel\Ncv\GridPal\ImgDataGradMgr_GridPal.h>
//#include <Lib\Novel\Ncv\GridPal\ImgDataMgr_2_FactorySet_GridPal.h>
//#include <Lib\Novel\Ncv\GridPal\ImgDataMgr_2_GridPal.h>

//#include <Lib\Novel\Ncv\ImgData_Simple\ImgDataGradMgr_Simple.h>
//#include <Lib\Novel\Ncv\ImgData_Simple\ImgDataMgr_2_FactorySet_Simple.h>
//#include <Lib\Novel\Ncv\ImgData_Simple\ImgDataMgr_2_Simple.h>

#include <Lib\Novel\Ncv\Binarization\ImgAngleDirMgr.h>
#include <Lib\Novel\Ncv\Binarization\AngleDirMgrColl.h>
#include <Lib\Novel\Ncv\Binarization\AngleDirMgrColl_Context.h>
//#include <Lib\Novel\Ncv\Binarization\RotationMgrColl.h>
#include <Lib\Novel\Ncv\Binarization\BinarizationProcess1.h>
#include <Lib\Novel\Ncv\Binarization\PixelInfo_1.h>











