
#include <NovelCVLib\Ncv\OpenCV\PixelTypes.cpp>
#include <NovelCVLib\Ncv\OpenCV\funcs1.cpp>
//#include <NovelCVLib\Ncv\ConvKernel.cpp>
#include <NovelCVLib\Ncv\OpenCV\Hsv.cpp>
//#include <NovelCVLib\Ncv\HistoGram.cpp>
#include <NovelCVLib\Ncv\InitLib.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor2.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor3.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor4.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor5.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor6.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor7.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor8.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor9.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor10.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor11.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor12.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor13.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor14.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor15.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor16.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor17.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor18.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor19.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor20.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor21.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor22.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor23.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor24.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor25.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor26.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor27.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor28.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor29.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor30.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor31.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor32.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor33.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor34.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor35.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor36.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor37.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor38.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor39.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor40.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor41.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor42.cpp>
//#include <NovelCVLib\Ncv\RegionSegmentor43.cpp>
//#include <NovelCVLib\Ncv\AdaptiveConv.cpp>
//#include <NovelCVLib\Ncv\AdaptiveConv2.cpp>
//#include <NovelCVLib\Ncv\CusteringTries.cpp>
//#include <NovelCVLib\Ncv\ClusteringMgr.cpp>
//#include <NovelCVLib\Ncv\ImageClusteringMgr.cpp>
//#include <NovelCVLib\Ncv\SignalOneDim.cpp>
//#include <NovelCVLib\Ncv\SobelBuilder.cpp>
//#include <NovelCVLib\Ncv\PNEdgeBuilder.cpp>
#include <NovelCVLib\Ncv\IOMgr.cpp>
#include <NovelCVLib\Ncv\LinePath.cpp>
#include <NovelCVLib\Ncv\LinePathInt.cpp>
#include <NovelCVLib\Ncv\Signal1D.cpp>
#include <NovelCVLib\Ncv\Signal1DViewer.cpp>
//#include <NovelCVLib\Ncv\Filter1D.cpp>
//#include <NovelCVLib\Ncv\ConvFilter1D.cpp>
//#include <NovelCVLib\Ncv\LinearColorFilter1D.cpp>
//#include <NovelCVLib\Ncv\LinearAvgFilter1D.cpp>
//#include <NovelCVLib\Ncv\LinearDiffFilter1D.cpp>
//#include <NovelCVLib\Ncv\ImageLineViewer.cpp>
//#include <NovelCVLib\Ncv\ColorFilter1D.cpp>
//#include <NovelCVLib\Ncv\CompositeColorFilter1D.cpp>
//#include <NovelCVLib\Ncv\ColorFilter1DSystem.cpp>
//#include <NovelCVLib\Ncv\AbsFilter1D.cpp>
//#include <NovelCVLib\Ncv\ScaleFixFilter1D.cpp>
//#include <NovelCVLib\Ncv\PeakCleanerFilter1D.cpp>
//#include <NovelCVLib\Ncv\PeakMarkerFilter1D.cpp>
//#include <NovelCVLib\Ncv\ValleyMaximizerFilter1D.cpp>
//#include <NovelCVLib\Ncv\ImageLineViewer2.cpp>
//#include <NovelCVLib\Ncv\ImageLineViewer3.cpp>
//#include <NovelCVLib\Ncv\SerialColorMgr.cpp>
//#include <NovelCVLib\Ncv\ConflictScanner.cpp>
//#include <NovelCVLib\Ncv\ConflictScanner2.cpp>
//#include <NovelCVLib\Ncv\FiltSysDebug.cpp>
//#include <NovelCVLib\Ncv\ValleyMarkerFilter1D.cpp>
//#include <NovelCVLib\Ncv\DiagonalLinePath.cpp>
//#include <NovelCVLib\Ncv\NegDiagonalLinePath.cpp>
//#include <NovelCVLib\Ncv\MaxFilter1D.cpp>
//#include <NovelCVLib\Ncv\BadRootScanner.cpp>
//#include <NovelCVLib\Ncv\CircleContPath.cpp>
//#include <NovelCVLib\Ncv\CircleContourOfPix.cpp>
//#include <NovelCVLib\Ncv\CircleContourOfPix2.cpp>
//#include <NovelCVLib\Ncv\CircleContourOfPix3.cpp>
//#include <NovelCVLib\Ncv\CircleContourOfPix4.cpp>
//#include <NovelCVLib\Ncv\CircleContourOfPix5.cpp>
#include <NovelCVLib\Ncv\MultiColorSignal1DViewer.cpp>
//#include <NovelCVLib\Ncv\CircDiff.cpp>
//#include <NovelCVLib\Ncv\CircDiff2.cpp>
//#include <NovelCVLib\Ncv\SlideMgr.cpp>
//#include <NovelCVLib\Ncv\LineStepper.cpp>
//#include <NovelCVLib\Ncv\LineStepperByAngle.cpp>
//#include <NovelCVLib\Ncv\ScanDirMgr.cpp>
//#include <NovelCVLib\Ncv\ImgDataMgr_Simple.cpp>
//#include <NovelCVLib\Ncv\ImgDataMgr_Simple_2.cpp>
//#include <NovelCVLib\Ncv\IImgDataMgr.cpp>
//#include <NovelCVLib\Ncv\ImgDataElm_Simple.cpp>
//#include <NovelCVLib\Ncv\ScanDirMgrColl.cpp>
//#include <NovelCVLib\Ncv\SubGradMgr.cpp>
//#include <NovelCVLib\Ncv\ImgGradMgr.cpp>
//#include <NovelCVLib\Ncv\ImgGradMgr_2.cpp>
//#include <NovelCVLib\Ncv\ImgAvgingMgr.cpp>
//#include <NovelCVLib\Ncv\Avging_ScanDirMgrExt.cpp>
//#include <NovelCVLib\Ncv\DeltaSignal.cpp>
//#include <NovelCVLib\Ncv\SingFilt1D2.cpp>
//#include <NovelCVLib\Ncv\Filt1D2DataMgr.cpp>
//#include <NovelCVLib\Ncv\AvgFilt1D2.cpp>
//#include <NovelCVLib\Ncv\Filt1D2System.cpp>
//#include <NovelCVLib\Ncv\Filt1D2SysProto.cpp>
//#include <NovelCVLib\Ncv\ScanTryMgr.cpp>
//#include <NovelCVLib\Ncv\DifFilt1D2.cpp>
//#include <NovelCVLib\Ncv\PeakMarkerFilt1D2.cpp>
//#include <NovelCVLib\Ncv\AbsFilt1D2.cpp>
//#include <NovelCVLib\Ncv\ZeroCrossingFilt1D2.cpp>
//#include <NovelCVLib\Ncv\MaxFilt1D2.cpp>
//#include <NovelCVLib\Ncv\EdgeScanMgr.cpp>
//#include <NovelCVLib\Ncv\EdgeScan.cpp>
//#include <NovelCVLib\Ncv\ScanTryMgr2.cpp>
//#include <NovelCVLib\Ncv\ScanTryMgr_3.cpp>
//#include <NovelCVLib\Ncv\ScanTryMgr_4.cpp>
//#include <NovelCVLib\Ncv\ScanTryDbg.cpp>
//#include <NovelCVLib\Ncv\ZeroCrossing_2_Filt1D2.cpp>
//#include <NovelCVLib\Ncv\Ptr_Filt1D2DataMgr.cpp>
//#include <NovelCVLib\Ncv\ImageWatershedMgr.cpp>
//#include <NovelCVLib\Ncv\IImgPopulation.cpp>
//#include <NovelCVLib\Ncv\ImgPopulation_Simple.cpp>











